### ISSUE TITLE
Unsigned Setup File

### ISSUE THREAD

**Issue by KorbsStudio** [FalixNodes-Software/Desktop-App#1]
Since the setup file is unsigned, this can cause chrome based browsers to detect it as a virus, even though the software does not contain any viruses.

I've tried signing in the past, I never managed to do it. So I need help on this one!

**Comment by EncryptedWeb** [comment]
try using Softicallus to create a install,er, they will cover te licenses that u need.

**Comment by KorbsStudio** [comment]
I’ll look into it, thanks for the suggestion.

**Comment by KorbsStudio** [comment]
Softaculous has a lot of software, not sure what I'm looking for.

**Comment by EncryptedWeb** [comment]
i ment the Setup creator, not the website thingy.

You have to sign the setup file.
There are many tools to do that.
Check https://installforge.net/

Good luck! :)

**Comment by KorbsStudio** [comment]
The setup file is already created with InstallForge

**Comment by KorbsStudio** [comment]
I know Advanced Installer can sign the setup file, but the publisher's name turns out different than I wanted it to be.

**Comment by KorbsStudio** [comment]
Alright, I looked into getting some work arounds inside of Advanced Installer:
![image](https://cdn.discordapp.com/attachments/727078597583700018/729463029313437726/unknown.png)

**Comment by KorbsStudio** [comment]
![image](https://imgur.com/b1RRhkj.png)
I created a file with [NextGen Widget Encrypt](https://www.ngwidgetsoftware.com/downloads/nextgen-widget-encryption/), which seems to work. 
I have created a .pfx file along with a .cer file.

**Comment by KorbsStudio** [comment]
*moved to Microsoft Store*

**Comment by KorbsStudio** [comment]
I assume Microsoft has updated their policy on some stuff, because they were fine with accepting previous submissions of the application 5 times already. I guess I'll stop updating the Microsoft Store version then as I don't feel like dealing with this, just like Snap it's a waste of my time during software development.
This means we're converting back to EXE and will have to test our auto updater again during pre-releases.

The following is expected to happened during the next few days:
 - Test old updater in demo software, already doing [here](https://github.com/KorbsStudio/electron-updater-example)
 - Convert Linux to AppImage(Auto updater does not work with DEB, RPM, or any other formats) 
   - Linux shouldn't be a problem, as signing files isn't required and getting the updater to work is fine
 - See if we can get auto updater to work on macOS(last time was a failure)

**Comment by KorbsStudio** [comment]
Windows will be offered a ZIP for now to prevent blocked downloads
