### ISSUE TITLE
Panel in app isn't working

### ISSUE THREAD

**Issue by PFilip08** [FalixNodes-Software/Desktop-App#10]
**Describe the bug**
Panel in app isn't working/loading. I tried use beta but the same issue.

**To Reproduce**
1. Open app
2. Go to 'Panel' tab
3. Click on 'Load Panel' button
4. Wait.
5. See error (error in Screenshots section)

**Expected behavior**
1. Open app
2. Go to 'Panel' tab
3. Click on 'Load Panel' button
4. Wait.
5. See panel.

**Screenshots**
![apperror](http://pfiliptech.tk/cdn/falixnodes/apperror.png)

**Desktop:**
 - OS: Linux "KDE neon User Edition"
 - Version 5.21 x86_64

**Comment by KorbsStudio** [comment]
This is for all beta versions of FalixNodes Software, something in Electron has stopped working.
Caused: Unknown

**Comment by KorbsStudio** [comment]
This issue is related to: https://github.com/electron/electron/issues/24171

**Comment by KorbsStudio** [comment]
Panel controls are working again in the version I'm still working on, this issue will be closed once it is confirmed and released.

**Comment by KorbsStudio** [comment]
This issue is occurring again:
![image](https://user-images.githubusercontent.com/51213244/121938727-2b0c4400-cd1a-11eb-8269-8b3563e28f47.png)

I'll look into this later.

**Comment by KorbsStudio** [comment]
The image below is v3.1.0 being worked on and the panel loading, I believe there may of been an issue in v3.0.0 causing the loading issues.

The image below is also a packaged version of the software and not used with `npm start`.

![image](https://user-images.githubusercontent.com/51213244/122126653-1013ff80-ce00-11eb-849b-83b0fe7714dc.png)

**Comment by KorbsStudio** [comment]
Will test again soon on Windows 10

**Comment by KorbsStudio** [comment]
Interesting, this could actually be an issue with Windows 10.

This image below is using the exact same code as I used on Linux, in the comment above.

![image](https://user-images.githubusercontent.com/51213244/122129024-7a7a6f00-ce03-11eb-9845-48819ab476b9.png)

**Comment by KorbsStudio** [comment]
Software does redirect the `webview` to the proper URL at least, but there is an issue happening.

I'm still debuggin.

![image](https://user-images.githubusercontent.com/51213244/122129940-da254a00-ce04-11eb-86c5-24d5d8f97880.png)

**Comment by PFilip08** [comment]
Maybe this isn't related to this issue but i get this (I tried reinstalling).
![obraz](https://user-images.githubusercontent.com/78141929/122130287-af081e00-ce37-11eb-9950-2616f5c82c0e.png)

**Comment by KorbsStudio** [comment]
That's outdated. @PFilip08 Please update.
Maybe set settings as well.
