### ISSUE TITLE
Software redirects to beta website

### ISSUE THREAD

**Issue by KorbsStudio** [FalixNodes-Software/Desktop-App#9]
When loading the software, it redirects itself to the software's website.

**Comment by PFilip08** [comment]
Yep

**Comment by KorbsStudio** [comment]
Problem found: News tab attempts to load news content from URL.
URL is invalid, therefore redirects to beta website.

**Comment by KorbsStudio** [comment]
Resolved: Create a valid URL on the software website to fix this issue.
